# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
- stage: Copy
  displayName: Copy Files
  jobs:  
  - job: Copy
    displayName: Copy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: CopyFilesOverSSH@0
    #   inputs:
    #     sshEndpoint: 'rupeshvm01-service-connection'
    #     sourceFolder: '$(System.DefaultWorkingDirectory)'
    #     contents: '**/*'
    #     targetFolder: '/tmp'
    #     readyTimeout: '20000'
    # - task: SSH@0
    #   inputs:
    #     sshEndpoint: 'rupeshvm01-service-connection'
    #     runOptions: 'inline'
    #     inline: 'hostname'
    #     readyTimeout: '20000'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'rupeshvm-rg-connection01'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          sudo apt-get install sshpass -y 
          sshpass -p $(rupeshvmpass) scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r $(System.DefaultWorkingDirectory)/* azureuser@52.172.177.109:/tmp
        addSpnToEnvironment: true
        failOnStandardError: true